
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class Bai4_25_9_2024 extends javax.swing.JFrame {

    /**
     * Creates new form Bai4_25_9_2024
     */
    public Bai4_25_9_2024() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbR = new javax.swing.JLabel();
        txtR = new javax.swing.JTextField();
        txtD = new javax.swing.JTextField();
        rdHCN = new javax.swing.JRadioButton();
        rdHTron = new javax.swing.JRadioButton();
        rdHVuong = new javax.swing.JRadioButton();
        lbChuVi = new javax.swing.JLabel();
        lbDienTich = new javax.swing.JLabel();
        txtChuVi = new javax.swing.JTextField();
        txtDienTich = new javax.swing.JTextField();
        btnThucHien = new javax.swing.JButton();
        btnTiepTuc = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbR.setForeground(new java.awt.Color(51, 51, 255));
        lbR.setText("Nhap R");

        txtD.setBackground(new java.awt.Color(204, 204, 204));
        txtD.setText("4");
        txtD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdHCN);
        rdHCN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdHCN.setForeground(new java.awt.Color(204, 0, 204));
        rdHCN.setText("Hinh Chu Nhat");

        buttonGroup1.add(rdHTron);
        rdHTron.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdHTron.setForeground(new java.awt.Color(255, 51, 255));
        rdHTron.setText("Hinh Tron");

        buttonGroup1.add(rdHVuong);
        rdHVuong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdHVuong.setForeground(new java.awt.Color(153, 51, 255));
        rdHVuong.setText("Hinh Vuong");

        lbChuVi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbChuVi.setForeground(new java.awt.Color(255, 51, 51));
        lbChuVi.setText("Chu vi");

        lbDienTich.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDienTich.setForeground(new java.awt.Color(255, 51, 51));
        lbDienTich.setText("Dien tich");

        btnThucHien.setBackground(new java.awt.Color(255, 255, 102));
        btnThucHien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThucHien.setText("Thuc Hien");
        btnThucHien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThucHienActionPerformed(evt);
            }
        });

        btnTiepTuc.setBackground(new java.awt.Color(255, 255, 102));
        btnTiepTuc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTiepTuc.setText("Tiep Tuc");
        btnTiepTuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiepTucActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(255, 255, 102));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThoat.setText("Thoat");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThucHien)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(btnTiepTuc)
                                .addGap(56, 56, 56)
                                .addComponent(btnThoat)))
                        .addContainerGap(75, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtD, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                    .addComponent(txtR)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbChuVi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbDienTich, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtChuVi, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDienTich, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdHVuong)
                            .addComponent(rdHTron, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdHCN, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbR)
                    .addComponent(txtR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdHTron))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(rdHVuong))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdHCN)
                    .addComponent(txtChuVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbChuVi))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDienTich)
                    .addComponent(txtDienTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThucHien)
                    .addComponent(btnTiepTuc)
                    .addComponent(btnThoat))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnTiepTucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiepTucActionPerformed
        // TODO add your handling code here:
        txtR.setText("");
        txtD.setText("");
        txtChuVi.setText("");
        txtDienTich.setText("");
        rdHCN.setSelected(false);
        rdHTron.setSelected(false);
        rdHVuong.setSelected(false);
    }//GEN-LAST:event_btnTiepTucActionPerformed

    private void btnThucHienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThucHienActionPerformed
        // TODO add your handling code here:
        try{
            
            String sR = txtR.getText();
            double fR = Double.parseDouble(sR);
            double ChuVi = 0;
            double DienTich = 0;
            if(rdHTron.isSelected())
            { 
                ChuVi = 2 * Math.PI * fR;
                DienTich = Math.PI * fR * fR;
            }
            else if(rdHCN.isSelected())
            {
                ChuVi = 2 * (fR+4);
                DienTich = fR * 4;
             }
            else if(rdHVuong.isSelected()){
                ChuVi = 4*fR;
                DienTich = fR * fR;
            }
             txtChuVi.setText(String.valueOf(ChuVi)); // Cập nhật giá trị vào JTextField
             txtDienTich.setText(String.valueOf(DienTich));
        
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(this, "Vui long nhap so hop le");
        }
 
    }//GEN-LAST:event_btnThucHienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai4_25_9_2024.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai4_25_9_2024.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai4_25_9_2024.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai4_25_9_2024.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai4_25_9_2024().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThucHien;
    private javax.swing.JButton btnTiepTuc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lbChuVi;
    private javax.swing.JLabel lbDienTich;
    private javax.swing.JLabel lbR;
    private javax.swing.JRadioButton rdHCN;
    private javax.swing.JRadioButton rdHTron;
    private javax.swing.JRadioButton rdHVuong;
    private javax.swing.JTextField txtChuVi;
    private javax.swing.JTextField txtD;
    private javax.swing.JTextField txtDienTich;
    private javax.swing.JTextField txtR;
    // End of variables declaration//GEN-END:variables
}
