
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class Bai5_25_09_2024 extends javax.swing.JFrame {
   private int[] arr; // Khai báo biến arr
    private int currentIndex; // Khai báo biến currentIndex

    /**
     * Creates new form Bai5_25_09_2024
     */
    public Bai5_25_09_2024() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNhapN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNhapPT = new javax.swing.JTextField();
        txtMangVuaNhap = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTinhTong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSapXep = new javax.swing.JTextField();
        btnNhap = new javax.swing.JButton();
        btnThucHien = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nhap so pt mang:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mang da nhap:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nhap phan tu:");

        txtNhapPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNhapPTActionPerformed(evt);
            }
        });

        txtMangVuaNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMangVuaNhapActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Tinh tong: ");

        txtTinhTong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTinhTongActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Sap xep: ");

        txtSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSapXepActionPerformed(evt);
            }
        });

        btnNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNhap.setForeground(new java.awt.Color(0, 51, 51));
        btnNhap.setText("Nhap");
        btnNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapActionPerformed(evt);
            }
        });

        btnThucHien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThucHien.setText("Thuc hien");
        btnThucHien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThucHienActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThoat.setText("Thoat");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMangVuaNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(txtTinhTong, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(txtSapXep)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtNhapN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNhapPT, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThucHien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNhapN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtNhapPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMangVuaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThucHien))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTinhTong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMangVuaNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMangVuaNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMangVuaNhapActionPerformed

    private void txtTinhTongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTinhTongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTinhTongActionPerformed

    private void txtSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSapXepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSapXepActionPerformed

    private void txtNhapPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNhapPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNhapPTActionPerformed

    private void btnNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapActionPerformed
        // TODO add your handling code here:
        // 1. Nhap so pt
//        String sNhapN = txtNhapN.getText();
//        int iNhapN = Integer.parseInt(sNhapN);
//       
//        // Khai bao mang
//        int []arr = new int[iNhapN];
//        // Xu ly button Nhap:
//        for(int i = 0 ;i<iNhapN; i++)
//        {
//           // 2. Nhap tung pt
//            String sNhapPT = txtNhapPT.getText();
//            arr[i] = Integer.parseInt(sNhapPT);
//            txtNhapPT.setText("");
//        }
//        // Xuat
//          StringBuilder builder = new StringBuilder("Mảng đã nhập: ");
//    for (int i = 0; i < iNhapN; i++) {
//        builder.append(arr[i]).append(" ");
//    }
//   
//    JOptionPane.showMessageDialog(this, builder.toString());
        
  // Lấy số phần tử cần nhập
    String sNhapN = txtNhapN.getText();
    int iNhapN = Integer.parseInt(sNhapN);

    // Nếu mảng chưa được khởi tạo, thì khởi tạo mảng
    if (arr == null) {
        arr = new int[iNhapN];
        currentIndex = 0; // Reset chỉ số hiện tại
        JOptionPane.showMessageDialog(this, "Nhập " + iNhapN + " phần tử vào mảng.");
    }

    // Kiểm tra nếu chưa nhập đủ phần tử thì tiếp tục nhập
    if (currentIndex < iNhapN) {
        String sNhapPT = txtNhapPT.getText();
        if (!sNhapPT.isEmpty()) {
            arr[currentIndex] = Integer.parseInt(sNhapPT);
            txtMangVuaNhap.setText(txtMangVuaNhap.getText() + sNhapPT + " "); // Hiển thị các phần tử vừa nhập
            txtNhapPT.setText(""); // Xóa trường nhập
            currentIndex++; // Tăng chỉ số
        }

        // Khi nhập đủ phần tử, hiện thông báo
        if (currentIndex == iNhapN) {
            JOptionPane.showMessageDialog(this, "Đã nhập đủ " + iNhapN + " phần tử.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Bạn đã nhập đủ số phần tử!");
    }
    
    }//GEN-LAST:event_btnNhapActionPerformed

    private void btnThucHienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThucHienActionPerformed
        // TODO add your handling code here:
        
         // Kiểm tra xem mảng đã được khởi tạo và đã nhập đủ phần tử chưa
    if (arr == null || currentIndex < arr.length) {
        JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ phần tử!");
        return;
    }

    // Tính tổng
    int sum = 0;
    for (int num : arr) {
        sum += num;
    }
    txtTinhTong.setText(String.valueOf(sum));

    // Sắp xếp mảng giảm dần
    java.util.Arrays.sort(arr);
    StringBuilder sortedArray = new StringBuilder();
    for (int i = arr.length - 1; i >= 0; i--) {
        sortedArray.append(arr[i]).append(" ");
    }
    txtSapXep.setText(sortedArray.toString());
        
    }//GEN-LAST:event_btnThucHienActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
      txtNhapN.setText("");
    txtNhapPT.setText("");
    txtMangVuaNhap.setText("");
    txtTinhTong.setText("");
    txtSapXep.setText("");
    arr = null; // Đặt lại mảng
    currentIndex = 0; // Reset chỉ số hiện tại
        
        
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai5_25_09_2024.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai5_25_09_2024.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai5_25_09_2024.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai5_25_09_2024.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai5_25_09_2024().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNhap;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThucHien;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtMangVuaNhap;
    private javax.swing.JTextField txtNhapN;
    private javax.swing.JTextField txtNhapPT;
    private javax.swing.JTextField txtSapXep;
    private javax.swing.JTextField txtTinhTong;
    // End of variables declaration//GEN-END:variables
}
